language: node_js
node_js: "6.11.0"

before_script:
 - rvm install 2.1
 - rvm use 2.1
 - gem install jekyll -v 3.1.6
 - . $HOME/.nvm/nvm.sh && nvm install 6.1 && nvm use 6.1
 - gem install jekyll-paginate
 - gem install jekyll-feed
 - npm install -g firebase-tools

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
 - rm -rf public
 - jekyll build -d public
 - firebase deploy --token "${FIREBASE_TOKEN}"


# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the deploy branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

